using Aspects.SyntaxReceivers;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;
using TypeInfo = Aspects.SourceGenerators.Common.TypeInfo;
using static Aspects.SourceGenerators.Diagnostics.Errors;

namespace Aspects.SourceGenerators.Base
{
    public abstract class TypeSourceGeneratorBase : ISourceGenerator
    {
        protected private abstract string Name { get; }

        protected private abstract TypeSyntaxReceiver SyntaxReceiver { get; }

        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => SyntaxReceiver);
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (context.SyntaxContextReceiver == SyntaxReceiver || context.SyntaxContextReceiver.Equals(SyntaxReceiver))
            {
                foreach (var typeInfo in SyntaxReceiver.IdentifiedTypes)
                {
                    if (!typeInfo.HasPartialModifier)
                        context.ReportDiagnostic(MissingPartialModifier(typeInfo.Symbol, Name));
                    else
                    {
                        var src = GeneratePartialType(typeInfo);
                        context.AddSource($"{typeInfo.Symbol.ContainingNamespace.ToDisplayString()}." +
                            $"{typeInfo.Name.Replace('<', '[').Replace('>', ']')}-{Name}.g.cs", SourceText.From(src, Encoding.UTF8));
                    }
                }
            }
        }

        protected private abstract string Dependencies(TypeInfo typeInfo);

        protected private abstract string ClassBody(TypeInfo typeInfo);

        private string GeneratePartialType(TypeInfo typeInfo)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");

            var dependencies = Dependencies(typeInfo);
            if(dependencies.Length > 0)
                sb.AppendLine(dependencies);

            sb.AppendLine();

            sb.AppendLine($"namespace {typeInfo.Symbol.ContainingNamespace.ToDisplayString()}");
            sb.AppendLine("{");
            sb.Append('\t');

            sb.AppendLine(typeInfo.Declaration);
            sb.AppendLine("\t{");

            sb.AppendLine(ClassBody(typeInfo).Replace("\n", "\n\t\t").Insert(0, "\t\t"));

            sb.AppendLine("\t}");
            sb.Append("}");

            return sb.ToString();
        }
    }
}
