//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspects {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Attribute : global::System.Configuration.ApplicationSettingsBase {
        
        private static Attribute defaultInstance = ((Attribute)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Attribute())));
        
        public static Attribute Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PropertyEvent_Equality_Check {
            get {
                return ((string)(this["PropertyEvent_Equality_Check"]));
            }
            set {
                this["PropertyEvent_Equality_Check"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PropertyEvent_Equality_NullableCheck {
            get {
                return ((string)(this["PropertyEvent_Equality_NullableCheck"]));
            }
            set {
                this["PropertyEvent_Equality_NullableCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PropertyEvent_Equality_EnumerableComparing {
            get {
                return ((string)(this["PropertyEvent_Equality_EnumerableComparing"]));
            }
            set {
                this["PropertyEvent_Equality_EnumerableComparing"] = value;
            }
        }
    }
}
