using Aspects.Attributes;
using Aspects.SourceGenerators.Base;
using Aspects.SourceGenerators.Common;
using Aspects.SourceGenerators.SyntaxReceivers;
using Microsoft.CodeAnalysis;
using System.Linq;
using System.Text;
using TypeInfo = Aspects.SourceGenerators.Common.TypeInfo;

namespace Aspects.SourceGenerators
{
    [Generator]
    public class PropertyChangedSourceGenerator : TypeSourceGeneratorBase
    {
        private protected override string Name { get; } = "PropertyChanged";

        private protected override TypeSyntaxReceiver SyntaxReceiver { get; }
            = new TypeSyntaxReceiver(Types.WithMembersWith<NotifyPropertyChangedAttribute>());

        protected private override string GeneratePartialType(TypeInfo typeInfo)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System.ComponentModel;");
            sb.AppendLine();

            sb.AppendLine($"namespace {typeInfo.Symbol.ContainingNamespace.ToDisplayString()}");
            sb.AppendLine("{");
            sb.Append('\t');

            sb.AppendLine(typeInfo.Declaration);
            sb.AppendLine("\t{");

            if (!typeInfo.Members.Any(sy => sy.Name == "PropertyChanged"))
            {
                sb.AppendLine("\t\tpublic event PropertyChangedEventHandler PropertyChanged;");
                sb.AppendLine();
            }

            var attributedFields = typeInfo
                .MembersWith<NotifyPropertyChangedAttribute>()
                .OfType<IFieldSymbol>()
                .ToArray();

            sb.AppendLine(PropertyCode(attributedFields[0]));
            for (int i = 1; i < attributedFields.Length; i++)
            {
                sb.AppendLine();
                sb.AppendLine(PropertyCode(attributedFields[i]));
            }

            sb.AppendLine("\t}");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string PropertyCode(IFieldSymbol field)
        {
            var name = Property.Name(field.Name);
            var sb = new StringBuilder();

            var type = field.Type.ToDisplayString();
            var enableNull = type.Length > 0 && type[type.Length - 1] == '?';

            if (enableNull)
                sb.AppendLine("#nullable enable");

            sb.AppendLine($"\t\tpublic {type} {name}");
            sb.AppendLine("\t\t{");
            sb.AppendLine(GetterCode(field));
            sb.AppendLine(SetterCode(field));
            sb.Append("\t\t}");

            if (enableNull)
            {
                sb.AppendLine();
                sb.Append("#nullable restore");
            }

            return sb.ToString();
        }

        private static string GetterCode(IFieldSymbol field)
        {
            return $"\t\t\tget => {field.Name};";
        }

        private static string SetterCode(IFieldSymbol field)
        {
            var name = Property.Name(field.Name);
            var sb = new StringBuilder();

            var attName = typeof(NotifyPropertyChangedAttribute).FullName;
            var attData = field.GetAttributes()
                .First(a => a.AttributeClass.ToDisplayString() == attName);

            var attribute = NotifyPropertyChangedAttribute.FromAttributeData(attData);
            if (attribute.Visibility == SetterVisibility.Public)
                sb.AppendLine("\t\t\tset");
            else
                sb.AppendLine($"\t\t\t{attribute.Visibility.ToDisplayString()} set");

            sb.AppendLine("\t\t\t{");
            if (!attribute.EqualityCheck)
                sb.AppendLine(SetField(field.Name, name, 4));
            else
            {
                if (!field.Type.IsReferenceType)
                    sb.AppendLine($"\t\t\t\tif (!{field.Name}.Equals(value))");
                else
                {
                    sb.AppendLine($"\t\t\t\tif (!({field.Name} is null) && !{field.Name}.Equals(value) " +
                        $"|| {field.Name} is null && !(value is null))");
                }
                sb.AppendLine("\t\t\t\t{");
                sb.AppendLine(SetField(field.Name, name, 5));
                sb.AppendLine("\t\t\t\t}");
            }
            sb.Append("\t\t\t}");

            return sb.ToString();
        }

        private static string SetField(string fieldName, string propName, int indent)
        {
            var sb = new StringBuilder();
            for (int i = 0; i < indent; i++)
                sb.Append('\t');
            sb.AppendLine($"{fieldName} = value;");
            for (int i = 0; i < indent; i++)
                sb.Append('\t');
            sb.Append($"PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof({propName})));");
            return sb.ToString();
        }
    }
}
